# Generated by Django 5.0.7 on 2024-07-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Real_Estate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image_url',
        ),
        migrations.AddField(
            model_name='property',
            name='photo_url',
            field=models.CharField(default='../src/assets/defaultProperty.jpg', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='user_photo',
            field=models.CharField(default='../src/assets/defaultUser.jpg', max_length=200),
        ),
    ]
