# Generated by Django 5.0.7 on 2024-07-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Real_Estate', '0002_remove_property_image_url_property_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
