# Generated by Django 5.0.7 on 2024-07-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Real_Estate', '0004_property_latitude_property_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='properties',
            field=models.ManyToManyField(related_name='users', to='Real_Estate.property'),
        ),
    ]
