# Generated by Django 5.0.7 on 2024-07-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Real_Estate', '0006_remove_booking_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photo_url',
            field=models.CharField(default='../../front-end/realEstatePlatform/src/assets/defaultProperty.jpg', max_length=200),
        ),
    ]
