# Generated by Django 5.0.7 on 2024-07-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Real_Estate', '0007_alter_property_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photo_url',
            field=models.CharField(default='../src/assets/defaultProperty.jpg', max_length=200),
        ),
    ]
